name = "Paramiko"
uuid = "c8acf7ad-ace2-4c62-8e9f-23553cb236fa"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
