name = "Paramiko"
uuid = "c8acf7ad-ace2-4c62-8e9f-23553cb236fa"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
VersionParsing = "81def892-9a0e-5fdd-b105-ffc91e053289"

[compat]
PyCall = "1.18.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
